import { writeFileSync, mkdirSync, readdirSync, readFileSync, existsSync } from "fs"
import { resolve } from "path"
import { logger } from "../../core/logger.js"
import { loadConfig, useConfig } from "../../core/config.js"
import "../../runtime/globals.js"

const FRAMEWORK_EXPORTS = [
  "defineGlyriaConfig",
  "GlyriaClient",
  "GlyriaCommand",
  "GlyriaUserCommand",
  "GlyriaMessageCommand",
  "GlyriaEvent",
  "EmbedV2Builder",
  "createReplyableContext",
  "hexToNumber",
  "GlyriaBus",
  "globalBus",
  "useCommands",
  "logger",
]

const EXTENSION = ".ts"

const extractExports = (filePath: string, importPath: string, userExports: string[]) => {
  const content = readFileSync(filePath, "utf-8")
  const matches = [...content.matchAll(/export\s+(?:const|function|class)\s+(\w+)/g)]
  for (const match of matches) {
    const key = match[1]
    userExports.push(`const ${key}: typeof import("../${importPath}")["${key}"]`)
  }
}

export const generate = async (enableModuleSDK = false) => {
  mkdirSync(".glyria", { recursive: true })
  process.env.GLYRIA_BOT_ROOT = enableModuleSDK ? "Bot" : ""
  await loadConfig()
  const config = useConfig()
  const userExports: string[] = []

  // ===== DYNAMIC SCAN DIRS FROM CONFIG =====
  const scanDirs = (config.dev?.autoImportDirs ?? ["utils", "composables"]).map(
    (dir) => `src/${dir}`,
  )
  const scanFiles = ["src/index"]

  const getBotPath = (path: string) => (enableModuleSDK ? `Bot/${path}` : path)

  // ===== SCAN MODULES =====
  if (config.modules && config.modules.length > 0) {
    for (const module of config.modules) {
      try {
        const moduleName = module
          .split("/")
          .pop()!
          .replace(/[^a-zA-Z0-9]/g, "")
        const globalName = moduleName.charAt(0).toUpperCase() + moduleName.slice(1)
        await import(module)
        userExports.push(`const ${globalName}: typeof import("${module}")`)
      } catch {
        logger.warn("Auto Imports", ` Module "${module}" not found — is it installed?`)
      }
    }
  }

  // ===== SCAN DIRS =====
  for (const dir of scanDirs) {
    const targetDir = getBotPath(dir)
    const fullDir = resolve(targetDir)
    if (!existsSync(fullDir)) continue
    const files = readdirSync(fullDir).filter((f) => f.endsWith(EXTENSION))
    for (const file of files) {
      const filePath = resolve(fullDir, file)
      extractExports(filePath, `${targetDir}/${file}`, userExports)
    }
  }

  // ===== SCAN FILES =====
  for (const file of scanFiles) {
    const targetFile = getBotPath(file)
    const filePath = resolve(`${targetFile}${EXTENSION}`)
    if (!existsSync(filePath)) continue
    extractExports(filePath, `${targetFile}${EXTENSION}`, userExports)
  }

  // ===== FILE CONTENT =====
  const frameworkLines = FRAMEWORK_EXPORTS.map(
    (e) => `const ${e}: typeof import("@glyria/bot")["${e}"]`,
  )
  const content = `// auto-generated by glyria - dont edit this file
export {}
declare global {
  const djs: typeof import("discord.js")
  ${[...frameworkLines, ...userExports].join("\n  ")}
}
`
  writeFileSync(".glyria/imports.d.ts", content)
  logger.success(
    "Auto Imports",
    "Generated .glyria/imports.d.ts with " + userExports.length + " user exports",
  )
}
